### ISSUE TITLE
Get Vercel website working correctly

### ISSUE THREAD

**Issue by lgdynamite** [lgdynamite/GeolocationProjectMod4#2]
Issue appears to be with a missing variable causing an error in completing the request,
Here is the important part of the log
Missing variable `handler` or `app` in file "api/index.py".
See the docs: https://vercel.com/docs/functions/serverless-functions/runtimes/python
LambdaError: RequestId: f0aa0c1a-8d8e-4f3e-bdbe-f850f34ba6ca Process exited before completing request
    at Lambda.<anonymous> (/home/devasc/.nvm/versions/node/v18.18.0/lib/node_modules/vercel/node_modules/@vercel/fun/src/index.ts:103:10)
    at Generator.next (<anonymous>)
    at fulfilled (/home/devasc/.nvm/versions/node/v18.18.0/lib/node_modules/vercel/node_modules/@vercel/fun/dist/src/index.js:24:58)

**Comment by lgdynamite** [comment]
Got all the variable's in correctly and also got that log all fixed, seems to be working correctly so we are good to go
